name: kolarc_makina_takip
description: Kolarc Makina Takip Uygulaması
publish_to: 'none'

version: 2.0.0+3

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.0
  file_picker: ^6.1.1
  device_preview: ^1.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  share_plus: ^7.1.0
  path_provider: ^2.1.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/depo_logo.png"
  remove_alpha_ios: true          
  background_color_ios: "#0F172A" 

# İŞTE EKSİK OLAN VE SİMGELERİ/RESİMLERİ GETİRECEK ASIL KISIM:
flutter:
  uses-material-design: true
  assets:
    - assets/depo_logo.png