name: kolarc_makina_takip # Projenizin adı (küçük harfler, alt çizgiler)
description: Kolarc Makina Takip Uygulaması # Projenizin kısa açıklaması
# pub.dev'e yanlışlıkla yayınlanmasını önlemek için aşağıdaki satır
publish_to: 'none' # pub.dev'de yayınlamak istemiyorsanız bu satırı tutun

# Uygulamanızın sürümü ve yapı numarası.
version: 2.0.0+21 # Sürüm: üç nokta ile ayrılmış üç sayı + isteğe bağlı yapı numarası

environment:
  sdk: ^3.0.0 # Projenizin Dart SDK sürüm gereksinimi

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.0
  file_picker: ^6.1.1 # (Veya sendeki sürümü)
  device_preview: ^1.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  share_plus: ^7.1.0
  path_provider: ^2.1.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # BUNU EKLE

# EN ALTA ŞU BLOĞU EKLE:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Seninkinin adı logo.png idi, ona yol veriyoruz.
   
 