// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1lRtU-_SWrwtfipjFJSmtHaUA-PB7dUc',
    appId: '1:380412778313:web:e749c36850256152c32c98',
    messagingSenderId: '380412778313',
    projectId: 'kolarcmakinatakip',
    authDomain: 'kolarcmakinatakip.firebaseapp.com',
    storageBucket: 'kolarcmakinatakip.firebasestorage.app',
    measurementId: 'G-DD1D276X62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNex94URF_tGc-pDAHfrcuk6fVMsei2g',
    appId: '1:380412778313:android:561d48e1897093c5c32c98',
    messagingSenderId: '380412778313',
    projectId: 'kolarcmakinatakip',
    storageBucket: 'kolarcmakinatakip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzc_RD6YZpcmsYLJ3lWrgQsP6ho8dHHOk',
    appId: '1:380412778313:ios:7bcf6cbcadeff1d5c32c98',
    messagingSenderId: '380412778313',
    projectId: 'kolarcmakinatakip',
    storageBucket: 'kolarcmakinatakip.firebasestorage.app',
    iosBundleId: 'com.example.makinaTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzc_RD6YZpcmsYLJ3lWrgQsP6ho8dHHOk',
    appId: '1:380412778313:ios:7bcf6cbcadeff1d5c32c98',
    messagingSenderId: '380412778313',
    projectId: 'kolarcmakinatakip',
    storageBucket: 'kolarcmakinatakip.firebasestorage.app',
    iosBundleId: 'com.example.makinaTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1lRtU-_SWrwtfipjFJSmtHaUA-PB7dUc',
    appId: '1:380412778313:web:829e10e14d7e039ac32c98',
    messagingSenderId: '380412778313',
    projectId: 'kolarcmakinatakip',
    authDomain: 'kolarcmakinatakip.firebaseapp.com',
    storageBucket: 'kolarcmakinatakip.firebasestorage.app',
    measurementId: 'G-MHLS793K8W',
  );
}
